# Traefik static configuration
# Most configuration is done via command line arguments in docker-compose.yml
# This file is kept for reference and can be used for additional static config

log:
  level: INFO

accessLog: {}
